name = "CP2Skyrmions"
uuid = "5a6bbd9f-7f67-4d35-8f8a-5c8c2031e87e"
authors = ["Hao Zhang <hzhangphys@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
